version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: mysql:8.0
     environment:
      - MYSQL_DATABASE=db_airline
      - MYSQL_PASSWORD=super
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=super
    ports:
      - "3306:3306"
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
